Pirostagram 사이트/apps/posts/urls.py
from django.urls import path
from .views import *

app_name = 'posts'

urlpatterns = [
    path('', main, name='main'),
    path('create/', create, name='create'),
    path('detail/<int:pk>/', detail, name='detail'),
    path('delete/<int:pk>/', delete, name='delete'), 
    path('like_ajax/', like_ajax, name='like_ajax'),
    path('create_comment_ajax/',create_comment_ajax, name='create_comment_ajax')  
]

Pirostagram 사이트/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.posts.urls')),
    path('users/', include('apps.users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Pirostagram 사이트/apps/posts/models.py
from django.db import models
from apps.users.models import User

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=25)
    content = models.TextField()
    photo = models.ImageField(blank=True, upload_to='posts/%Y%m%d')
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    likes = models.ManyToManyField(User, through='Like', related_name='liked_posts')
    likes_count = models.IntegerField(default=0)
    dislikes = models.ManyToManyField(User, through='DisLike', related_name='disliked_posts')
    dislikes_count = models.IntegerField(default=0)

class Comment(models.Model):
    content = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

class DisLike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    

Pirostagram 사이트/apps/posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'photo']

Pirostagram 사이트/apps/posts/views.py
from django.shortcuts import render, redirect
from .models import Post, Like, DisLike
from .forms import PostForm
from django.contrib.auth.decorators import login_required

# Create your views here.

def main(request):
    posts = Post.objects.all()
    ctx = {
        'posts' : posts
    }
    return render(request, 'posts/post_list.html', ctx)

@login_required
def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)#아직 완전히 저장되기 전에 임시 객체로 불러옴
            post.user = request.user
            post.save()

            # Like 객체 생성, 연결
            like = Like(user=request.user, post=post)
            like.save()

            # DisLike 객체 생성, 연결
            dislike = DisLike(user=request.user, post=post)
            dislike.save()
            
            return redirect('posts:main')
        else:
            ctx = {
                'form' : form,#제대로된 폼이 아니니까 작성된 부분은 저장해서 다시 작성 페이지로 가기
            }
            return render(request, 'posts/post_create.html', ctx)
    elif request.method == 'GET':
        form = PostForm
        ctx = {
            'form' : form,
        }
        return render(request, 'posts/post_create.html', ctx)

def detail(request, pk):
    post = Post.objects.get(id=pk)
    ctx = {
        'post' : post,
    }
    return render(request, 'posts/post_detail.html', ctx)

def delete(request,pk):
    if request.method == "POST" :
        post = Post.objects.get(id=pk)
        post.delete()
    return redirect("posts:main")

import json
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def like_ajax(request) :
    req = json.loads(request.body)
    post_id = req['id']
    button_type = req['type']

    post = Post.objects.get(id=post_id)

    if button_type == 'likes_count':
        post.likes_count += 1
    else:
        post.dislikes_count += 1

    post.save()

    return JsonResponse({'id' : post_id, 'type' : button_type})

@csrf_exempt
def create_comment_ajax(request):
    if request.method == "POST":
        post_id = request.POST.get('post_id')
        content = request.POST.get('content')

        response_data = {
            'comment_id' : comment_id,
            'content':content,
        }
        return JsonResponse(response_data)

Pirostagram 사이트/templates/posts/post_create.html
{% extends 'base.html' %}

{% block content %}
<div class="create_container">
    <form action="{% url 'posts:create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %} {{form}}
        <button>Post</button>
    </form>
</div>
{% endblock %}

Pirostagram 사이트/templates/posts/post_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="main_container">
        {% for post in posts %}
            <div class="card_container post-id-{{post.id}}">
                <div class="card_body">
                    <div class="post_user">{{post.user.name}}</div>
                    {% if post.photo.url != '' %}
                        <img class="post_photo" src="{{post.photo.url}}" alt="대체텍스트">
                    {% else %}
                        <img class="post_photo" src="{% static 'post/image/no_image.png' %}" alt="대체텍스트">
                    {% endif %}
                    <div class="post_img"></div>
                    <div class="card_title"><a href="{% url 'posts:detail' post.pk %}">{{post.title}}</a></div>
                    <div class="card_content">{{post.content}}</div>
                    <div class="card_btn post_like" onclick="onClickLike({{post.id}}, 'likes_count')">❤️ {{post.likes_count}}</div>
                    <div class="card_btn post_dislike" onclick="onClickLike({{post.id}}, 'dislikes_count')">👎 {{post.dislikes_count}}</div>
                    <button onclick="createComment({{post.id}})">댓글 작성</button>
                    {% for comment in post.comments %}
                        <div class="comment-content">
                            {{comment.content}}
                            <button onclick="deleteComment({{comment.id}})">댓글 삭제</button>
                        </div>
                    {% endfor %}
                    <form action="{% url 'posts:delete' post.pk %}" method="post">
                        {%csrf_token%}
                        <button>삭제</button>
                    </form>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

{% block extra %}
<script>
    const requestLike = new XMLHttpRequest();

    const onClickLike = (id, type) => {
        const url = "/like_ajax/";
        
        requestLike.open("POST", url, true);
        requestLike.setRequestHeader(
            "Content-Type",
            "application/x-www-form-urlencoded"
        );

        requestLike.send(JSON.stringify({id:id, type:type}));
    }

    requestLike.onreadystatechange = () => {
        if (requestLike.readyState === XMLHttpRequest.DONE) {
            if(requestLike.status < 400) {
                const {id, type} = JSON.parse(requestLike.response);
                const element = document.querySelector(`.post-id-${id} .post_${type}`);
                const originHTML = element.innerHTML;
                const [buttonType, num] = originHTML.split(" ");
                const count = Number(num) + 1;

                element.innerHTML = `${buttonType} ${count}`;
            }
        };
    };
    // 댓글작성
    const requestCreateComment = new XNLHttpRequest();

    const createComment = (postId) => {
        const content = prompt('댓글 내용을 입력하세요.');

        const url = "/create_comment_ajax/";
        requestCreateComment.open("POST", url, true);
        requestCreateComment.setRequestHeader(
            "Content-Type",
            "application/x-www-form-urlencoded"
        );
        requestCreateComment.send(`post_id=${postId}&content=${content}`);
    }

    requestCreateComment.onreadystatechange = () => {
        if (requestCreateComment.readyState === XMLHttpRequest.DONE) {
            if (requestCreateComment.status < 400) {
                const { comment_id, content } = JSON.parse(requestCreateComment.response);
                const element = document.querySelector(`.post-id-${id} .comment-${content}`)
                
                element.innerHTML = `${content}`
            }
        }
    }
    // 댓글삭제
    const requestDeleteComment = new XMLHttpRequest();

    const deleteComment = (commentId) => {
        const url = "/delete_comment_ajax/";
        requestDeleteComment.open("POST", url, true);
        requestDeleteComment.setRequestHeader(
            "Content-Type",
            "application/x-www-form-urlencoded"
        );
        requestDeleteComment.send(`comment_id=${commentId}`);
    }

    requestDeleteComment.onreadystatechange = () => {
        if(requestDeleteComment.readyState == XMLHttpRequest.DONE) {
            if (requestDeleteComment.status < 400) {
                //클라이언트에서 댓글 삭제 로직 구현
            }
        }
    }

</script>

{%endblock%}