SWIDEA_SITE/apps/ideas/urls.py
from django.urls import path
from .views import *

app_name = 'ideas'

urlpatterns = [
    path('', main, name='main'),
    path('create/', create, name='create'),
    path('detail/<int:pk>/', detail, name='detail'),
    path('delete/<int:pk>/', delete, name='delete'),
    path('update/<int:pk>/', update, name='update'),
]

SWIDEA_SITE/apps/tools/urls.py
from django.urls import path
from .views import *

app_name = 'tools'

urlpatterns = [
    path('list/', tool_list, name='list'),
    path('create/', create, name='create'),
    path('detail/<int:pk>', detail, name="detail"),
    path('update/<int:pk>', update, name="update"),
    path('delete/<int:pk>', delete, name="delete"),
]

SWIDEA_SITE/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.ideas.urls')),
    path('tools/', include('apps.tools.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SWIDEA_SITE/apps/ideas/models.py
from django.db import models
from apps.tools.models import Tool

# Create your models here.

class Idea(models.Model):
    title = models.CharField('아이디어명:', max_length=24)
    photo = models.ImageField('Image:', blank=True, upload_to='images/%Y%m%d')
    content = models.TextField('아이디어 설명:')
    like = models.IntegerField('아이디어 관심도:', default=0)
    tool = models.ForeignKey(Tool, on_delete=models.CASCADE, verbose_name='예상 개발툴:')
    created_at = models.DateTimeField('작성일', auto_created=True, auto_now_add=True)
    

SWIDEA_SITE/apps/tools/models.py
from django.db import models

# Create your models here.
class Tool(models.Model):
    title = models.CharField('이름:', max_length=24)
    type = models.CharField('종류:', max_length=24)
    content = models.TextField('개발툴 설명:')

    def __str__(self):
        return self.title

SWIDEA_SITE/apps/ideas/forms.py
from django import forms
from .models import Idea

class IdeaForm(forms.ModelForm):
    class Meta():
        model = Idea
        fields = ('__all__')

SWIDEA_SITE/apps/tools/forms.py
from django import forms
from .models import Tool

class ToolForm(forms.ModelForm):
    class Meta():
        model = Tool
        fields = ('__all__')

SWIDEA_SITE/apps/ideas/views.py
from django.shortcuts import render,redirect
from .models import Idea
from .forms import IdeaForm

# Create your views here.
def main(request):
    sort_order = request.GET.get('sort', 'name')
    if sort_order == 'name':
        ideas = Idea.objects.order_by('title')
    elif sort_order == 'created':
        ideas = Idea.objects.order_by('created_at')
    elif sort_order == 'like':
        ideas = Idea.objects.order_by('-like')
    else:
        ideas = Idea.objects.all()
    # ideas = Idea.objects.all()
    ctx = {'ideas': ideas}
    return render(request, 'ideas/idea_list.html', ctx)

def create(request):
    if request.method == 'GET':
        form = IdeaForm()
        ctx = {'form': form}
        return render(request, 'ideas/idea_create.html', ctx)
    form = IdeaForm(request.POST, request.FILES)
    if form.is_valid():
        form.save()
    return redirect('ideas:main')

def detail(request, pk):
    idea = Idea.objects.get(id=pk)
    ctx = {'idea': idea}
    return render(request, 'ideas/idea_detail.html', ctx)

def delete(request, pk):
    if request.method == 'POST':
        Idea.objects.get(id=pk).delete()
    return redirect('ideas:main')

def update(request, pk):
    idea = Idea.objects.get(id=pk)
    if request.method == 'GET':
        form = IdeaForm(instance=idea)
        ctx = {'form': form, 'pk':pk}
        return render(request, 'ideas/idea_update.html', ctx)
    
    form = IdeaForm(request.POST, request.FILES, instance=idea)
    if form.is_valid():
        form.save()
    return redirect('ideas:detail', pk)

    

SWIDEA_SITE/apps/tools/views.py
from django.shortcuts import render, redirect
from .models import Tool
from .forms import ToolForm
from apps.ideas.models import Idea
# Create your views here.

def tool_list(request):
    tools = Tool.objects.all()
    ctx = {'tools': tools}
    return render(request, 'tools/tool_list.html', ctx)

def create(request):
    if request.method == 'GET':
        form = ToolForm()
        ctx = {'form': form}
        return render(request, 'tools/tool_create.html', ctx)
    form=ToolForm(request.POST)
    if form.is_valid():
        form.save()
    return redirect('tools:list')

def detail(request, pk):
    tool = Tool.objects.get(id=pk)
    ideas = Idea.objects.all()
    related_ideas = []
    for idea in ideas:
        if idea.tool.title == tool.title:
            related_ideas.append(idea)

    ctx = {'tool' : tool,
           'related_ideas' : related_ideas}
    return render(request, 'tools/tool_detail.html', ctx)


def delete(request, pk):
    if request.method == 'POST':
        Tool.objects.get(id=pk).delete()
    return redirect('tools:list')

def update(request, pk):
    tool = Tool.objects.get(id=pk)
    if request.method == 'GET':
        form = ToolForm(instance=tool)
        ctx = {'form': form, 'pk': pk}
        return render(request, 'tools/tool_update.html', ctx)
    form = ToolForm(request.POST, instance=tool)
    if form.is_valid():
        form.save()
    return redirect('tool:detail', pk)

SWIDEA_SITE/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SWIDEA_SITE</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link
    href="https://cdn.jsdelivr.net/npm/remixicon@4.1.0/fonts/remixicon.css"
    rel="stylesheet"/>
    <script defer src="{% static 'ideas/js/scripts.js' %}"></script>
</head>
<body>
    <header>
        <h1><a href="/">My SW ideas Manage</a></h1>
        <p><a href="{% url 'ideas:create' %}">아이디어 등록</a></p>
        <p><a href="{% url 'ideas:main' %}">아이디어 관리</a></p>
        <p><a href="{% url 'tools:create' %}">개발도구 등록</a></p>
        <p><a href="{% url 'tools:list' %}">개발도구 관리</a></p>
    </header>
    <div class="total_container">
        {% block content %}
    
        {% endblock %}
    </div>
    
</body>
</html>

SWIDEA_SITE/templates/ideas/idea_create.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="sub_title">
        <h2>Idea Register</h2>
    <p>아이디어등록 페이지 입니다. 당신의 아이디어를 잊지말고 기록하세요!</p>
    </div>

    <form class="form_container"action="{% url 'ideas:create' %}" 
    method="post" 
    enctype="multipart/form-data">
        {% csrf_token %} {{form.as_p}}
        <button >submit</button>
    </form>
{% endblock %}

SWIDEA_SITE/templates/ideas/idea_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="sub_title">
        <h2>idea Detail</h2>
        <p>아이디어 세부내용 페이지 입니다. 당신이 구현하려 한 아잉디어를 자세히 살펴보세요.</p>
    </div>

    {% if idea.photo.url != '' %}
        <img src="{{idea.photo.url}}" alt="이미지">
    {% else %}
        <img src="{% static 'ideas/image/no_img.png' %}" alt="대체 텍스트">
    {% endif %}
    <p class="title">{{idea.title}}</p>
    <p class="like">1) 아이디어 관심도 <br>{{idea.like}}</p>
    <p class="tool"><a href="{% url 'tools:detail' idea.tool.pk %}">2) 예상 개발 툴 <br>{{idea.tool.title}}</a></p>
    <p class="content">3) 아이디어 설명 <br>{{idea.content}}</p>

    <form action="{% url 'ideas:delete' idea.pk %}" method="POST">
        {% csrf_token %}
        <button type="submit">삭제</button>
        <a href="{%url 'ideas:main' %}">목록</a>
        <a href="{%url 'ideas:update' idea.pk %}">수정</a>
        
    </form>
{% endblock %}

SWIDEA_SITE/templates/ideas/idea_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="sub_title">
        <h2 class="sub_title_one">Idea List</h2>
        <p>나의 아이디어를 잊지말고 기록해보세요</p>
    </div>

    <label for="sort">정렬 순서:</label>
    <select name="sort" id="sort" onchange="changeSort(this)">
        <option value="default">정렬순</option>
        <option value="name">이름순</option>
        <option value="created">등록순</option>
        <option value="like">관심도순</option>
    </select>

    <script>
        function changeSort(select) {
            var sortValue = select.value;
            window.location.href = "{% url 'ideas:main' %}?sort=" + sortValue;
        }
    </script>

    <div class="item_container">
        {% for idea in ideas %}
            <div class="item">
                {% if idea.photo.url != null and idea.photo.url != '' %}
                    <img src="{{ idea.photo.url }}" alt="대체텍스트">
                {% else %}
                    <img src="{% static 'ideas/image/no_img.png' %}" alt="대체텍스트">
                {% endif %}
                <div class="info">
                    <a href="{% url 'ideas:detail' idea.pk %}" class="title">{{idea.title}}</a>
                    <p class="tool">{{idea.tool}}</p>
                    <div class="like">
                        <i class="ri-add-line" id="plus"></i>
                        <p class="like" data-like="{{idea.like}}">{{idea.like}}</p>
                        <i class="ri-subtract-line" id="minus"></i>
                    </div>
                </div>   
            </div>
        {% endfor %}
    </div>
    
{% endblock %}

SWIDEA_SITE/templates/ideas/idea_update.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="sub_title">
        <h2>Idea Detail Update</h2>
        <p>아이디어 세부내용 수정 페이지 입니다. 아이디어를 구체화하거나 내용을 변경해 보아요.</p>
    </div>
    <form action="{% url 'ideas:update' pk%}"
    method="post"
    enctype="multipart/form-data">
    {%csrf_token%} {{form.as_p}}
    <button>수정완료</button>
    </form>
{% endblock %}

SWIDEA_SITE/templates/tools/tool_create.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="sub_title">
        <h2>DevTool Register</h2>
        <p>개발툴 등록 페이지 입니다. 자신이 다룰 수 있는 개발툴을 등록해 보세요.</p>
    </div>
    <form action="{% url 'tools:create' %}" method="post">
        {%csrf_token%} {{form.as_p}}
        <button>submit</button>
    </form>
{% endblock %}

SWIDEA_SITE/templates/tools/tool_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="sub_title">
        <h2>DevTool Detail</h2>
        <p>개발툴 세부내용 페이지 입니다. 자신이 다룰 수 있는 개발툴에 대한 상세내용을 확인해 보아요.</p>
    </div>
    <div class="tool_item">
        <p class="tool_title">{{tool.title}}</p>
        <p class="tool_type">{{tool.type}}</p>
        <p class="tool_content">{{tool.content}}</p>
        <p>>만들 수 있는 SW 목록</p>
        {% for rel_idea in related_ideas %}
            <a href="{% url 'ideas:detail' rel_idea.pk %}">
                {{rel_idea.title}} <br>
            </a>
        {% endfor %}
    </div>

    <form action="{% url 'tools:delete' tool.pk %}" method="POST">
        {%csrf_token%}
        <button >삭제</button>
        <a href="{% url 'tools:list' %}">목록</a>
        <a href="{% url 'tools:update' tool.pk %}">수정</a>
    </form>
{% endblock %}

SWIDEA_SITE/templates/tools/tool_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="sub_title">
        <h2>DevTool List</h2>
        <p>개발툴 목록 페이지 입니다. 자신이 사용가능한 개발들의 목록을 확인해 보세요.</p>
    </div>
    {% for tool in tools %}
        <div class="tool_item">
            <p><a href="{% url 'tools:detail' tool.pk %}">{{tool.title}}</a></p>
            <p>{{tool.type}}</p>
            <p>{{tool.content}}</p>
        </div>
    {% endfor %}
{% endblock %}

SWIDEA_SITE/templates/tools/tool_update.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="sub_title">
        <h2>DevTool Detail Update</h2>
        <p>개발툴 세부내용 수정 페이지 입니다. 개발툴에 대해 수정사항이 있으면 고쳐보아요.</p>
    </div>
    <form action="{% url 'tools:update' pk %}" method="POST">
        {%csrf_token%} {{form.as_p}}
        <button>submit</button>
    </form>
{% endblock %}